export const ProfitSplitterABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_registry", type: "address", internalType: "address" },
      { name: "_asset", type: "address", internalType: "address" },
      { name: "_treasury", type: "address", internalType: "address" },
      { name: "_protocolFeeBps", type: "uint256", internalType: "uint256" },
      { name: "_creatorShareBps", type: "uint256", internalType: "uint256" },
      { name: "_epochDuration", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BPS_DENOMINATOR",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_CREATOR_SHARE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_PROTOCOL_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "agentVault",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "asset",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "canDistribute",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "ok", type: "bool", internalType: "bool" },
      { name: "secondsRemaining", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creatorShareBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "distributeProfit",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "protocolFee", type: "uint256", internalType: "uint256" },
      { name: "creatorShare", type: "uint256", internalType: "uint256" },
      { name: "subscriberShare", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "epochDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastEpochTs",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastSnapshot",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFeeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolTreasury",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerVault",
    inputs: [
      { name: "agentId", type: "uint256", internalType: "uint256" },
      { name: "vault", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registry",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IAgentRegistry" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreatorShare",
    inputs: [{ name: "newBps", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEpochDuration",
    inputs: [{ name: "secs", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProtocolFee",
    inputs: [{ name: "newBps", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTreasury",
    inputs: [{ name: "newTreasury", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CreatorShareUpdated",
    inputs: [
      {
        name: "oldBps",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newBps",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProfitDistributed",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "grossProfit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "protocolFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "creatorShare",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "subscriberShare",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "epochTimestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolFeeUpdated",
    inputs: [
      {
        name: "oldBps",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newBps",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SnapshotTaken",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "ts", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TreasuryUpdated",
    inputs: [
      {
        name: "oldTreasury",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "newTreasury",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VaultRegisteredInSplitter",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "vault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ProfitSplitter__AlreadyRegistered",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "ProfitSplitter__EpochNotElapsed",
    inputs: [
      { name: "earliest", type: "uint256", internalType: "uint256" },
      { name: "now_", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ProfitSplitter__InvalidCreatorShareBps",
    inputs: [
      { name: "bps", type: "uint256", internalType: "uint256" },
      { name: "max", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ProfitSplitter__InvalidEpochDuration",
    inputs: [
      { name: "given", type: "uint256", internalType: "uint256" },
      { name: "min", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ProfitSplitter__InvalidProtocolFeeBps",
    inputs: [
      { name: "bps", type: "uint256", internalType: "uint256" },
      { name: "max", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "ProfitSplitter__NoProfit", inputs: [] },
  {
    type: "error",
    name: "ProfitSplitter__VaultNotRegistered",
    inputs: [{ name: "vault", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ProfitSplitter__ZeroAsset", inputs: [] },
  { type: "error", name: "ProfitSplitter__ZeroRegistry", inputs: [] },
  { type: "error", name: "ProfitSplitter__ZeroTreasury", inputs: [] },
] as const;
