export const AgentRegistryABI = [
  {
    type: "constructor",
    inputs: [{ name: "owner_", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "agentCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deactivateAgent",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executorAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveAgentsPaginated",
    inputs: [
      { name: "offset", type: "uint256", internalType: "uint256" },
      { name: "limit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "page",
        type: "tuple[]",
        internalType: "struct IAgentRegistry.AgentInfo[]",
        components: [
          { name: "creator", type: "address", internalType: "address" },
          { name: "vaultAddress", type: "address", internalType: "address" },
          { name: "createdAt", type: "uint96", internalType: "uint96" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "pad0", type: "uint8", internalType: "uint8" },
          { name: "pad1", type: "uint16", internalType: "uint16" },
          { name: "totalSubscribers", type: "uint32", internalType: "uint32" },
          {
            name: "totalVolumeTraded",
            type: "uint128",
            internalType: "uint128",
          },
          { name: "name", type: "string", internalType: "string" },
          { name: "strategyType", type: "string", internalType: "string" },
        ],
      },
      { name: "total", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgent",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IAgentRegistry.AgentInfo",
        components: [
          { name: "creator", type: "address", internalType: "address" },
          { name: "vaultAddress", type: "address", internalType: "address" },
          { name: "createdAt", type: "uint96", internalType: "uint96" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "pad0", type: "uint8", internalType: "uint8" },
          { name: "pad1", type: "uint16", internalType: "uint16" },
          { name: "totalSubscribers", type: "uint32", internalType: "uint32" },
          {
            name: "totalVolumeTraded",
            type: "uint128",
            internalType: "uint128",
          },
          { name: "name", type: "string", internalType: "string" },
          { name: "strategyType", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgentByVault",
    inputs: [{ name: "vault", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IAgentRegistry.AgentInfo",
        components: [
          { name: "creator", type: "address", internalType: "address" },
          { name: "vaultAddress", type: "address", internalType: "address" },
          { name: "createdAt", type: "uint96", internalType: "uint96" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "pad0", type: "uint8", internalType: "uint8" },
          { name: "pad1", type: "uint16", internalType: "uint16" },
          { name: "totalSubscribers", type: "uint32", internalType: "uint32" },
          {
            name: "totalVolumeTraded",
            type: "uint128",
            internalType: "uint128",
          },
          { name: "name", type: "string", internalType: "string" },
          { name: "strategyType", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorAgents",
    inputs: [{ name: "creator_", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isActive",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reactivateAgent",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerAgent",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "strategyType", type: "string", internalType: "string" },
      { name: "vaultAddress", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setExecutor",
    inputs: [{ name: "executor_", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSubscriberCount",
    inputs: [
      { name: "agentId", type: "uint256", internalType: "uint256" },
      { name: "increment", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateVolumeTraded",
    inputs: [
      { name: "agentId", type: "uint256", internalType: "uint256" },
      { name: "volume", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AgentDeactivated",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "by", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentReactivated",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "by", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentRegistered",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "vaultAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      {
        name: "strategyType",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SubscriberCountUpdated",
    inputs: [
      {
        name: "agentId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newCount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AgentRegistry__AgentAlreadyActive",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "AgentRegistry__AgentNotActive",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "AgentRegistry__AgentNotFound",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "AgentRegistry__EmptyName", inputs: [] },
  { type: "error", name: "AgentRegistry__EmptyStrategyType", inputs: [] },
  { type: "error", name: "AgentRegistry__InvalidVaultAddress", inputs: [] },
  {
    type: "error",
    name: "AgentRegistry__NotCreator",
    inputs: [
      { name: "caller", type: "address", internalType: "address" },
      { name: "expected", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "AgentRegistry__Unauthorized",
    inputs: [{ name: "caller", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AgentRegistry__VaultAlreadyRegistered",
    inputs: [{ name: "vault", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
] as const;
